# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /data/kind/master
      containerPath: /data
# - role: control-plane
# - role: worker
# - role: worker
# - role: worker
#   extraMounts:
#     - hostPath: /data/kind/worker
#       containerPath: /data
