apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: kube-system
spec:
  addresses:
    - 172.18.0.200-172.18.0.255
---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: empty
#   namespace: kube-system
