apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-istio"},"spec":{"acme":{"email":"infra@reclameaqui.com.br","privateKeySecretRef":{"name":"letsencrypt-istio"},"server":"https://acme-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"istio"}},"selector":{}}]}}}
  creationTimestamp: "2021-09-24T15:30:29Z"
  generation: 1
  name: letsencrypt-istio
  resourceVersion: "1437929"
  uid: 25cc8750-06fc-4411-89de-a20c33af3406
spec:
  acme:
    email: infra@reclameaqui.com.br
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-istio
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: istio
      selector: {}
status:
  acme:
    lastRegisteredEmail: infra@reclameaqui.com.br
    uri: https://acme-v02.api.letsencrypt.org/acme/acct/111806389
  conditions:
  - lastTransitionTime: "2021-09-24T15:30:30Z"
    message: The ACME account was registered with the ACME server
    observedGeneration: 1
    reason: ACMEAccountRegistered
    status: "True"
    type: Ready
