apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-cert
  namespace: istio-system
  # annotations:
  #   "cert-manager.io/issue-temporary-certificate": "true"
spec:
  secretName: gitlab-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - rpolnx
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: gitlab-pvt.rpolnx.com.br
  dnsNames:
  - "*.gitlab-pvt.rpolnx.com.br"