apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-vs
  namespace: tools
spec:
  gateways:
  - gitlab-gateway
  hosts:
  - gitlab-pvt.rpolnx.com.br
  http:
  - name: "gitlab-v1-router"
    route:
    - destination:
        host: gitlab-webservice-default
        port:
          number: 8080