apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  name: wf-suspend-template #unique identifier of workflow instead of generated name
spec:
  entrypoint: steps-template-suspend
  templates:
    - name: steps-template-suspend
      steps:
        - - name: step1
            template: task-template
        - - name: step2
            template: task-template
          - name: step3
            template: task-template
        - - name: delay
            template: delay-template
        - - name: step4
            template: task-template

    - name: task-template
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          print("Task template serial executed")
    - name: delay-template
      suspend:
        duration: "10s"
