{{- if .Values.istio.enabled -}}
{{- if .Values.istio.tls.enabled }}
{{- if .Values.istio.certmanager.enabled }}
{{- if .Values.istio.certmanager.production.enabled }}
apiVersion: cert-manager.io/v1
{{- else }}
apiVersion: certmanager.k8s.io/v1alpha1  
{{- end }}
kind: Certificate
metadata:
  name: {{ .Values.istio.tls.secret }}
  labels:
{{ include "gateway.labels" . | indent 4 }}
  namespace: istio-system
spec:
  dnsNames: {{- range .Values.istio.hosts }}
  - {{.}}{{- end }}
  secretName: {{ .Values.istio.tls.secret }}
  {{- if .Values.istio.certmanager.issuerRef }}
  issuerRef:
{{ toYaml .Values.istio.certmanager.issuerRef | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}