apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpolnx-local-vs
spec:
  gateways:
  - rpolnx-local-gateway
  hosts:
  - "*.rpolnx.local"
  http:
  - name: "basic-router"
    # match:
    # - uri:
    #     prefix: "/nginx"
    # rewrite:
    #   uri: "/"
    route:
    - destination:
        host: nginx
        port:
          number: 80
        # subset: v1
